# ----
# Site

title: Hakemy Docs
url: "https://hanyakita-group.github.io/hakemy-docs"
baseurl: "https://hanyakita-group.github.io/hakemy-docs"
google_analytics_key:
show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: Hisam
  email: hisamcode@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Hakemy Docs
  links:
    - https://hanyakita-group.github.io/hakemy-docs

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  
collections:
  posts:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000


prose:
  rooturl: '_posts'
  siteurl: 'https://hanyakita-group.github.io/hakemy-docs/'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Information Gathering"
              value: "Information Gathering"
            - name: "Research And Planing"
              value: "Research And Planing"
            - name: "Design And Prototiping"
              value: "Design And Prototiping"
            - name: "POC"
              value: "POC"
            - name: "Development"
              value: "Development"
            - name: "Staging"
              value: "Staging"
            - name: "Deployment"
              value: "Deployment"
            - name: "Go Live"
              value: "Go Live"
      - name: "order"
        field:
          element: "text"
          label: "Order"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
