# ----
# Site

title: Hakemy Docs
url: "https://hanyakita-group.github.io/hakemy-docs"
baseurl: "https://hanyakita-group.github.io/hakemy-docs"
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: Hisam
  email: hisamcode@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Hakemy Docs
  links:
    - https://hanyakita-group.github.io/hakemy-docs

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE


prose:
  rooturl: '_posts'
  siteurl: 'http://joshuacox.github.io/'
  relativeLinks: 'http://joshuacox.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "Category"
        field:
          element: "text"
          label: "category"
          value: ""
      - name: "Order"
        field:
          element: "text"
          label: "order"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false